### ISSUE TITLE
detect filetype in the same way vim does, instead of by file extention

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#32]
I have no idea how vim does it, so idk if it would work, but its worth at least looking at.

It's annoying that syntax highlighting doesn't work when editing files without the right file extension, for example, neofetch is a bash script, but since it has no file name extention, there is no syntax highlighting.

**Comment by kyx0r** [comment]
Hello, I've made a patch that demonstates how you can detect and set filetype via shebang.
It should be obvious if you need to add anything to it or expand on the idea.
Have a look here:
https://github.com/kyx0r/nextvi/commit/714629e766169585f36e7e8f38f702f69050f1cc

**Comment by OldWorldOrdr** [comment]
hey, i just noticed the patch doesn't work in combination with stdin_pipe.patch, catting a file with a shebang and piping it into `vi -` doesn't use syntax highlighting

**Comment by kyx0r** [comment]
It does not work because the stdin_pipe.patch does not use the same function to read the data. I pushed a change to make it work and I fixed the pipe suspend issue for stdin_pipe.patch just now too.

Thanks for reporting, I am delighted to hear your ideas, whatever they may be. If you need some other feature just ask me, most likely I will implement it as a patch.

Kind Regards,
Kyryl

**Comment by OldWorldOrdr** [comment]
thanks
