### ISSUE TITLE
does nextvi support tags?

### ISSUE THREAD

**Issue by LinArcX** [kyx0r/nextvi#36]
I was using Neovim user for a long. and I was using LSP for getting a lot of information about the codebase that I'm working on. like, jump to the definition of methods,...

Then I realized that LSP is bloated for me and tags are enough. and I really like the simplicity of tags in comparison to LSP.

so with ctags, I can start creating tags for my project, and with `:tag` i can jump between functions.

I couldn't find tags in nextvi. It doesn't support it?

If not, what is the alternative?

**Comment by polluks** [comment]
@LinArcX FYI since two weeks https://github.com/aligrudi/neatvi supports its own tag tool.

**Comment by dostoievsky** [comment]
Hello. I am trying using grep.patch, when I do C-x, I am taken to the /grep/ buffer, but nothing shows, how can I specify what I am searching for?

**Comment by kyx0r** [comment]
Hi @dostoievsky!

Thanks for asking, I'm going to explain how you would use fssearch first -
1. Compute the directory you want using the ex command :fd
2. :fd without arg will compute the current working dir, but you can also do something like fd .. or fd /whatever/path
3. Also, you don't have to use fd, you can do something like :b-2|1,1!find or even just load it from a file.
4. If you are using :fd, then you can use :inc as well to narrow it down to only directories that you want, otherwise it's irrelevant.
5. You can quickly check the result of that using ex command :b-2 or the \ key from normal mode in vi
6. Once you have the directory listing that you want, you can use the fssearch, it only searches the files in /fm/ buffer
7. Next, to do fssearch you have to set the search keyword. There are many ways to do this:
* the fastest is to put a cursor on whatever text you want and use command from normal mode 1^] (1 is vi_arg1 and it will set the keyword to 1 word under the cursor, give it 3 and it be 3 words, etc, etc).
* the other way is to use v/ from normal and just type what you want. Or do 1v/ and it will bring words from the cursor into that prompt.
* and lastly, using searches like / ? ^a also will set that keyword
8. Once the keyword is set, you don't have to set it again, just use keybinds ^] and ^p to jump between results.
9. One thing to note is that it does only 1 match per file, so if there are many results, you can just use n and N to check.

Now that you know how to set a directory and the keyword, using grep.patch becomes trivial -
1. Just use ^x or 1^x (if keyword needed)
2. vx is quick shortcut to access the /grep/ buffer
3. When you are inside /grep/ buffer you can use ^i to go to whatever the match is.
4. You can also use keybind ^6 to swap to previous buffer

Some additional tips on :fd - and ^x
When inside /fm/ or /grep/ use [ and ] marks (the keybind be '[ and ']) to visually determine the latest block that was added.
Example command for :fd blah and then :fd bruh and then :fd muh or combined :b-2|fd blah|bs|fd bruh|bs|fd muh

**Comment by dostoievsky** [comment]
Thank you very much, this is awesome!

**Comment by kyx0r** [comment]
> Thank you very much, this is awesome! I tried to use :fd with arguments but it seens to returns nothing.
> 
> If I am using arguments, the arguments then must be directories that will have files searches, that is it?

Correct.
