### ISSUE TITLE
ex: parsing seems still broken

### ISSUE THREAD

**Issue by polluks** [kyx0r/nextvi#46]
```
echo 'foo | bar' > file1; echo 'foo/bar' > file2;
vi
:edit +1 | s/|/PIPE/ | w file1 | e file2 | 1 | s/\//SLASH/ | wq
```
See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html#tag_20_40_18_08

**Comment by kyx0r** [comment]
Nextvi does not support this syntax and there are many problems that I see.
At the very least try correct syntax.

:e +1 | s/\\|/PIPE/ | w file1 | e file2 | 1 | s/\//SLASH/ | wq

**Comment by kyx0r** [comment]
Although the ranges in edit command are not supported. So e +1 probably
isn't what you need to use, just use 1

**Comment by polluks** [comment]
My strange result of "1"
```
-rw-r--r--  1 polluks  wheel  10 23 Jul 05:49 file1
-rw-------  1 polluks  wheel   0 23 Jul 05:49 file1 
-rw-r--r--  1 polluks  wheel   8 23 Jul 05:49 file2
-rw-------  1 polluks  wheel   0 23 Jul 05:49 file2 
$ cat -n file?
     1	foo | bar
     1	foo/bar

**Comment by kyx0r** [comment]
I think you're not reading the file1, replace edit +1 with e file1, also
\\| results in | bar, but thats a syntax error in regular expression,
probably need 1 more slash, \\\|

I can't quite test this right now. I'm pretty sure this is caused by user
error.

-Kyryl

**Comment by polluks** [comment]
I see, the files are not doppelgangers but have a trailing space!

**Comment by kyx0r** [comment]
So the correct command would be:
e file1|s/\|/PIPE/ | w! file1| e file2| 1 | s/\//SLASH/|wq

w! is needed here as you give it same argument will error with "file exists"
you can just use w alone, but just for the sake of being use w!.

I don't really expect production commands to have spaces between the bars, they are not necessary and ambiguous since the space would be passed into resulting ex function and its a gamble weather that function will ignore or not ignore the trailing space. 

The only thing I may wanna refactor is the | escapes. I don't think its the special casing is necessary anymore, original idea was to reduce number of slashes for most common uses like \\| and \| but its rather hard to explain how it works. probably just 1 extra slash can make more sense. Only issue is when using commands like vr, it will not correctly auto escape the | characters, which is probably why this rule was made in the first place.

**Comment by kyx0r** [comment]
You should try/test the new ex | escape syntax I committed, should be more self explanatory now. 

```e file1|s/\\|/PIPE/ | w! file1| e file2| 1 | s/\//SLASH/|wq```

\| for |
\\| for \|
\\\| for \\|

etc...

**Comment by polluks** [comment]
close...
```
$ cat -n file?
     1	PIPEfoo | bar
     1	fooSLASHbar

**Comment by kyx0r** [comment]
Didn't escape the | properly.
