### ISSUE TITLE
Adding the ability to use custom keyboad layouts?

### ISSUE THREAD

**Issue by ghost** [kyx0r/nextvi#51]
Some people may want to customize their keybinding a little bit without spending hours looking "Oh I forgot to change this switch statement."

An example of that is changing `hjkl` to characters used by other keyboard layouts (not languages, just layouts like colemak and workman), `yneo` and `neio` would be good examples.

A simple translation array should be enough for most uses.

**Comment by kyx0r** [comment]
You have a point, this can be done with translation array and a few code changes. But I don't see the need to have this in base version as extra checks slow down input performance.

Would me making a patch that does this and published on patches branch suit your needs? (Although I'm going to do it either way since the patch is ready now.)

Kind Regards,
Kyryl

**Comment by kyx0r** [comment]
You can use this and customize to your liking:

https://github.com/kyx0r/nextvi/blob/patches/kbd_layout.patch

**Comment by jumps-are-op** [comment]
Oh, never thought of making a patch for that. Thank you so much!
