### ISSUE TITLE
Ctrl+V causes segmentation fault

### ISSUE THREAD

**Issue by Vouivre** [kyx0r/nextvi#9]
Hello,

sometimes I need to insert some tabs, not spaces, really some tabs. As far as I know, to insert some tabs I need to do the following:

Ctrl+V  Tab

Unfortunately, I get a `Segmentation fault`. 

Steps to reproduce: 

- open `nextvi`
- `i` to  enter the insert mode
- write "Hello"
-  press "Ctrl+V" always in insert mode

Then I get a `Segmentation fault` 

The shortcut "Ctrl+V" in normal mode seems to work fine. I had to insert some tabs in the past and it worked without problem. 

I have tested with the latest git version. Do you get the same ?

**Comment by kyx0r** [comment]
Hello Cedric,

Recently I've loosened up the requirement for ^v so that It could be used
from insert to bring history commands from insert mode, but if you had no
previous commands that entered in prompt. Actually, history buffer is not
created/allocated until the first time you run the ex prompt. There are 2
solutions:

1. Create a history buffer on startup
2. Check if it's created everytime ^v keybind is used
3. Create history buffer from insert mode

Tbh, I don't like any of these, 1. nextvi is specifically designed
not to run any extra startup code except compiling regular expressions.
2. Seems OK, but likely 2 extra lines of code to cover the edge case
3. This is an extra if statement in insert that would always have to run,
which hypothetically would affect performance of vi macros.

Which solution makes the most sense to you?
I suppose I am stressing over trivial matters here, but still this is
interesting design question. Most of the time how edge cases are
handled determine how well code is designed, it's always best
to handle them implicitly.

**Comment by kyx0r** [comment]
Went with solution 1, yes extra empty malloc at startup but I sorta answered by own question there :)

**Comment by kyx0r** [comment]
Tabs? To insert tabs the ASCII key for that always have been the TAB or ^i or you can use key binds ^t or ^d (delete tab) this pretty much has never changed. Previously ^v did nothing in insert mode, in neatvi ^v allowed typing a string literal, nextvi also has this but it is bound to ^a key (in insert). See (47.) to type tab using ^a    ^a^i   though this is not necessary in this case.

**Comment by Vouivre** [comment]
Thank you for your response! 

By the way I discovered ^t which is really interesting. I didn't know about ^i, it will replace "^v tab" for me. 

I would have chosen also the solution 1. Thank you for the fix and the exhaustive answer!
