### ISSUE TITLE
ex "!"

### ISSUE THREAD

**Issue by polluks** [kyx0r/nextvi#99]
Why does standard `:r !date` not work? (neatvi requires the space)

**Comment by kyx0r** [comment]
Hello Stefan, I'm glad you asked. Nextvi is special in that by default ! in ex commands expands the result of pipe command into the command itself. It doesn't work because what you're really doing is this:
```
:r Thu Apr  4 08:13:22 EDT 2024
```

It can't read that file. To get the standard result you want to just escape the !
```
:r \!date
```

This is also documented in feature 22. It mentions  :w command as an example but might not be so obvious for :r.
